import upstox_api.utils as ut

ALL_CONTRACTS = ['acc', 'adanient', 'adaniports', 'adanipower', 'ajantpharm', 'albk', 'amarajabat', 'ambujacem', 'andhrabank', 'apollohosp', 'apollotyre', 'arvind', 'ashokley', 'asianpaint', 'auropharma', 'axisbank', 'bajaj-auto', 'bajajfinsv', 'bajfinance', 'balkrisind', 'balramchin', 'bankbaroda', 'bankindia', 'bataindia', 'bel', 'beml', 'bergepaint', 'bharatfin', 'bharatforg', 'bhartiartl', 'bhel', 'biocon', 'boschltd', 'bpcl', 'britannia', 'cadilahc', 'canbk', 'canfinhome', 'capf', 'castrolind', 'ceatltd', 'centurytex', 'cesc', 'cgpower', 'chennpetro', 'cholafin', 'cipla', 'coalindia', 'colpal', 'concor', 'cumminsind', 'dabur', 'dalmiabha', 'dcbbank', 'dhfl', 'dishtv', 'divislab', 'dlf', 'drreddy', 'eichermot', 'enginersin', 'equitas', 'escorts', 'exideind', 'federalbnk', 'gail', 'glenmark', 'gmrinfra', 'godfryphlp', 'godrejcp', 'godrejind', 'granules', 'grasim', 'gsfc', 'havells', 'hcc', 'hcltech', 'hdfc', 'hdfcbank', 'heromotoco', 'hexaware', 'hindalco', 'hindpetro', 'hindunilvr', 'hindzinc', 'ibulhsgfin', 'icicibank', 'icicipruli', 'idbi', 'idea', 'idfc', 'idfcbank', 'ifci', 'igl', 'indiacem', 'indianb', 'indigo', 'indusindbk', 'infibeam', 'infratel', 'infy', 'ioc', 'irb', 'itc', 'jetairways', 'jindalstel', 'jisljaleqs', 'jpassociat', 'jswsteel', 'jublfood', 'justdial', 'kajariacer', 'kotakbank', 'kpit', 'kscl', 'ktkbank', 'l&tfh', 'lichsgfin', 'lt', 'lupin', 'm&m', 'm&mfin', 'manappuram', 'marico', 'maruti',  'mcx', 'mfsl', 'mgl', 'mindtree', 'mothersumi', 'mrf', 'mrpl', 'muthootfin', 'nationalum', 'nbcc', 'ncc', 'nestleind', 'nhpc', 'niittech', 'nmdc', 'ntpc', 'ofss', 'oil', 'ongc', 'orientbank', 'pageind', 'pcjeweller', 'pel', 'petronet', 'pfc', 'pidilitind', 'pnb', 'powergrid', 'ptc', 'pvr', 'ramcocem', 'raymond', 'rblbank', 'rcom', 'recltd', 'relcapital', 'reliance', 'relinfra', 'repcohome', 'rpower', 'sail', 'sbin', 'shreecem', 'siemens', 'southbank', 'sreinfra', 'srf', 'srtransfin', 'star', 'sunpharma', 'suntv', 'suzlon', 'syndibank', 'tatachem', 'tatacomm', 'tataelxsi', 'tataglobal', 'tatamotors', 'tatamtrdvr', 'tatapower', 'tatasteel', 'tcs', 'techm', 'titan', 'torntpharm', 'torntpower', 'tv18brdcst', 'tvsmotor', 'ubl', 'ujjivan', 'ultracemco', 'unionbank', 'upl', 'vedl', 'vguard', 'voltas', 'wipro', 'wockpharma', 'yesbank', 'zeel']
OHLC_5MIN="5MINUTE"
OHLC_10MIN="10MINUTE"
OHLC_30MIN="30MINUTE"
OHLC_60MIN="60MINUTE"
OHLC_DAY="1DAY"
OHLC_WEEK="1WEEK"
OHLC_MONTH="1MONTH"