from setuptools import setup

setup(
    name='abhyan',
    version='1.0',
    packages=['conf', 'venv.Lib.site-packages.bs4', 'venv.Lib.site-packages.bs4.tests',
              'venv.Lib.site-packages.bs4.builder', 'venv.Lib.site-packages.cffi', 'venv.Lib.site-packages.fpdf',
              'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.lxml', 'venv.Lib.site-packages.lxml.html',
              'venv.Lib.site-packages.lxml.includes', 'venv.Lib.site-packages.lxml.isoschematron',
              'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.click', 'venv.Lib.site-packages.nsepy',
              'venv.Lib.site-packages.nsepy.debt', 'venv.Lib.site-packages.nsepy.indices',
              'venv.Lib.site-packages.nsepy.derivatives', 'venv.Lib.site-packages.numpy',
              'venv.Lib.site-packages.numpy.ma', 'venv.Lib.site-packages.numpy.ma.tests',
              'venv.Lib.site-packages.numpy.doc', 'venv.Lib.site-packages.numpy.fft',
              'venv.Lib.site-packages.numpy.fft.tests', 'venv.Lib.site-packages.numpy.lib',
              'venv.Lib.site-packages.numpy.lib.tests', 'venv.Lib.site-packages.numpy.core',
              'venv.Lib.site-packages.numpy.core.tests', 'venv.Lib.site-packages.numpy.f2py',
              'venv.Lib.site-packages.numpy.f2py.tests', 'venv.Lib.site-packages.numpy.tests',
              'venv.Lib.site-packages.numpy.compat', 'venv.Lib.site-packages.numpy.compat.tests',
              'venv.Lib.site-packages.numpy.linalg', 'venv.Lib.site-packages.numpy.linalg.tests',
              'venv.Lib.site-packages.numpy.random', 'venv.Lib.site-packages.numpy.random.tests',
              'venv.Lib.site-packages.numpy.testing', 'venv.Lib.site-packages.numpy.testing.tests',
              'venv.Lib.site-packages.numpy.testing._private', 'venv.Lib.site-packages.numpy.distutils',
              'venv.Lib.site-packages.numpy.distutils.tests', 'venv.Lib.site-packages.numpy.distutils.command',
              'venv.Lib.site-packages.numpy.distutils.fcompiler', 'venv.Lib.site-packages.numpy.matrixlib',
              'venv.Lib.site-packages.numpy.matrixlib.tests', 'venv.Lib.site-packages.numpy.polynomial',
              'venv.Lib.site-packages.numpy.polynomial.tests', 'venv.Lib.site-packages.wrapt',
              'venv.Lib.site-packages.pandas', 'venv.Lib.site-packages.pandas.io',
              'venv.Lib.site-packages.pandas.io.sas', 'venv.Lib.site-packages.pandas.io.json',
              'venv.Lib.site-packages.pandas.io.formats', 'venv.Lib.site-packages.pandas.io.msgpack',
              'venv.Lib.site-packages.pandas.io.clipboard', 'venv.Lib.site-packages.pandas.api',
              'venv.Lib.site-packages.pandas.api.types', 'venv.Lib.site-packages.pandas.api.extensions',
              'venv.Lib.site-packages.pandas.core', 'venv.Lib.site-packages.pandas.core.util',
              'venv.Lib.site-packages.pandas.core.tools', 'venv.Lib.site-packages.pandas.core.arrays',
              'venv.Lib.site-packages.pandas.core.dtypes', 'venv.Lib.site-packages.pandas.core.sparse',
              'venv.Lib.site-packages.pandas.core.groupby', 'venv.Lib.site-packages.pandas.core.indexes',
              'venv.Lib.site-packages.pandas.core.reshape', 'venv.Lib.site-packages.pandas.core.computation',
              'venv.Lib.site-packages.pandas.util', 'venv.Lib.site-packages.pandas._libs',
              'venv.Lib.site-packages.pandas._libs.tslibs', 'venv.Lib.site-packages.pandas.tests',
              'venv.Lib.site-packages.pandas.tests.io', 'venv.Lib.site-packages.pandas.tests.io.sas',
              'venv.Lib.site-packages.pandas.tests.io.json', 'venv.Lib.site-packages.pandas.tests.io.parser',
              'venv.Lib.site-packages.pandas.tests.io.formats', 'venv.Lib.site-packages.pandas.tests.io.msgpack',
              'venv.Lib.site-packages.pandas.tests.api', 'venv.Lib.site-packages.pandas.tests.util',
              'venv.Lib.site-packages.pandas.tests.frame', 'venv.Lib.site-packages.pandas.tests.tools',
              'venv.Lib.site-packages.pandas.tests.dtypes', 'venv.Lib.site-packages.pandas.tests.scalar',
              'venv.Lib.site-packages.pandas.tests.scalar.period',
              'venv.Lib.site-packages.pandas.tests.scalar.interval',
              'venv.Lib.site-packages.pandas.tests.scalar.timedelta',
              'venv.Lib.site-packages.pandas.tests.scalar.timestamp', 'venv.Lib.site-packages.pandas.tests.series',
              'venv.Lib.site-packages.pandas.tests.series.indexing', 'venv.Lib.site-packages.pandas.tests.sparse',
              'venv.Lib.site-packages.pandas.tests.sparse.frame', 'venv.Lib.site-packages.pandas.tests.sparse.series',
              'venv.Lib.site-packages.pandas.tests.tslibs', 'venv.Lib.site-packages.pandas.tests.generic',
              'venv.Lib.site-packages.pandas.tests.groupby', 'venv.Lib.site-packages.pandas.tests.groupby.aggregate',
              'venv.Lib.site-packages.pandas.tests.indexes', 'venv.Lib.site-packages.pandas.tests.indexes.period',
              'venv.Lib.site-packages.pandas.tests.indexes.interval',
              'venv.Lib.site-packages.pandas.tests.indexes.datetimes',
              'venv.Lib.site-packages.pandas.tests.indexes.timedeltas', 'venv.Lib.site-packages.pandas.tests.reshape',
              'venv.Lib.site-packages.pandas.tests.reshape.merge', 'venv.Lib.site-packages.pandas.tests.tseries',
              'venv.Lib.site-packages.pandas.tests.tseries.offsets', 'venv.Lib.site-packages.pandas.tests.indexing',
              'venv.Lib.site-packages.pandas.tests.indexing.interval', 'venv.Lib.site-packages.pandas.tests.plotting',
              'venv.Lib.site-packages.pandas.tests.extension', 'venv.Lib.site-packages.pandas.tests.extension.base',
              'venv.Lib.site-packages.pandas.tests.extension.json',
              'venv.Lib.site-packages.pandas.tests.extension.decimal',
              'venv.Lib.site-packages.pandas.tests.extension.category', 'venv.Lib.site-packages.pandas.tests.internals',
              'venv.Lib.site-packages.pandas.tests.categorical', 'venv.Lib.site-packages.pandas.tests.computation',
              'venv.Lib.site-packages.pandas.tools', 'venv.Lib.site-packages.pandas.types',
              'venv.Lib.site-packages.pandas.compat', 'venv.Lib.site-packages.pandas.compat.numpy',
              'venv.Lib.site-packages.pandas.errors', 'venv.Lib.site-packages.pandas.formats',
              'venv.Lib.site-packages.pandas.tseries', 'venv.Lib.site-packages.pandas.plotting',
              'venv.Lib.site-packages.pandas.computation', 'venv.Lib.site-packages.certifi',
              'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli', 'venv.Lib.site-packages.pymysql',
              'venv.Lib.site-packages.pymysql.constants', 'venv.Lib.site-packages.urllib3',
              'venv.Lib.site-packages.urllib3.util', 'venv.Lib.site-packages.urllib3.contrib',
              'venv.Lib.site-packages.urllib3.contrib._securetransport', 'venv.Lib.site-packages.urllib3.packages',
              'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.dateutil',
              'venv.Lib.site-packages.dateutil.tz', 'venv.Lib.site-packages.dateutil.parser',
              'venv.Lib.site-packages.dateutil.zoneinfo', 'venv.Lib.site-packages.requests',
              'venv.Lib.site-packages.pycparser', 'venv.Lib.site-packages.pycparser.ply',
              'venv.Lib.site-packages.asn1crypto', 'venv.Lib.site-packages.asn1crypto._perf',
              'venv.Lib.site-packages.sqlalchemy', 'venv.Lib.site-packages.sqlalchemy.ext',
              'venv.Lib.site-packages.sqlalchemy.ext.declarative', 'venv.Lib.site-packages.sqlalchemy.orm',
              'venv.Lib.site-packages.sqlalchemy.sql', 'venv.Lib.site-packages.sqlalchemy.util',
              'venv.Lib.site-packages.sqlalchemy.event', 'venv.Lib.site-packages.sqlalchemy.engine',
              'venv.Lib.site-packages.sqlalchemy.testing', 'venv.Lib.site-packages.sqlalchemy.testing.suite',
              'venv.Lib.site-packages.sqlalchemy.testing.plugin', 'venv.Lib.site-packages.sqlalchemy.dialects',
              'venv.Lib.site-packages.sqlalchemy.dialects.mssql', 'venv.Lib.site-packages.sqlalchemy.dialects.mysql',
              'venv.Lib.site-packages.sqlalchemy.dialects.oracle', 'venv.Lib.site-packages.sqlalchemy.dialects.sqlite',
              'venv.Lib.site-packages.sqlalchemy.dialects.sybase',
              'venv.Lib.site-packages.sqlalchemy.dialects.firebird',
              'venv.Lib.site-packages.sqlalchemy.dialects.postgresql', 'venv.Lib.site-packages.sqlalchemy.databases',
              'venv.Lib.site-packages.sqlalchemy.connectors', 'venv.Lib.site-packages.cryptography',
              'venv.Lib.site-packages.cryptography.x509', 'venv.Lib.site-packages.cryptography.hazmat',
              'venv.Lib.site-packages.cryptography.hazmat.backends',
              'venv.Lib.site-packages.cryptography.hazmat.backends.openssl',
              'venv.Lib.site-packages.cryptography.hazmat.bindings',
              'venv.Lib.site-packages.cryptography.hazmat.bindings.openssl',
              'venv.Lib.site-packages.cryptography.hazmat.primitives',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.kdf',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.ciphers',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.twofactor',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.asymmetric',
              'venv.Lib.site-packages.pandas_datareader', 'venv.Lib.site-packages.pandas_datareader.av',
              'venv.Lib.site-packages.pandas_datareader.io', 'venv.Lib.site-packages.pandas_datareader.iex',
              'venv.Lib.site-packages.pandas_datareader.mstar', 'venv.Lib.site-packages.pandas_datareader.tests',
              'venv.Lib.site-packages.pandas_datareader.tests.av', 'venv.Lib.site-packages.pandas_datareader.tests.io',
              'venv.Lib.site-packages.pandas_datareader.tests.mstar',
              'venv.Lib.site-packages.pandas_datareader.tests.yahoo',
              'venv.Lib.site-packages.pandas_datareader.tests.google', 'venv.Lib.site-packages.pandas_datareader.yahoo',
              'venv.Lib.site-packages.pandas_datareader.compat', 'venv.Lib.site-packages.pandas_datareader.google',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip', 'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.operations', 'utils', 'classes'],
    url='',
    license='',
    author='Nagaraju',
    author_email='tradeuser2018@gmail.com',
    description='Trade Analysis'
)
